Add a python code example
WISVCH/payments pull request #27
Opened 2017-03-14 12:30 UTC by martijnjanssen

2017-03-14 16:44 UTC, praseodym requested changes

2017-03-14 16:44 UTC, praseodym commented on README.md
> +        'returnUrl': 'https://www.ch.tuldeft.nl/payments/ordercompleted',
tuldeft

2017-03-14 16:44 UTC, praseodym commented on README.md
> +        'email': 'thomasticket@mail.com',
voor dit soort dingen is er example.com

2017-03-14 18:31 UTC, praseodym approved these changes

2017-03-15 09:04 UTC, skamoen commented
Congratulations on your first uilenballen!

2017-03-15 09:04 UTC, merged